# Site settings
title: 와치
email: watchnem@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: 
url: https://watchnem.github.io # the base hostname & protocol for your site
twitter_username: watch_nn

# Build settings
markdown: kramdown
permalink: /:year-:month-:day-:title
# https://github.com/midzer/urban-theme?tab=readme-ov-file

permitted_categories:
  - 로아
  - 베르뷰
  - 자림
  - 니린
  - 애커
  - 감자
  - 개멍이
  - 고냥어
  - 곽효인
  - 군쌤
  - 기묭묭지
  - 김도아
  - 낑깡
  - 댕님
  - 라쿤씨
  - 레몬
  - 레임
  - 령라떼
  - 로라
  - 로_압생트
  - 루화
  - 류뻔뻔
  - 말차당고
  - 메뭄
  - 모코
  - 미천용사
  - 미코
  - 밀키웨이
  - 뱅
  - 버니버니
  - 빙빙수
  - 사월
  - 산설아
  - 세빛
  - 수정
  - 순후추
  - 아츠
  - 아포
  - 안절부절
  - 애망애망
  - 영태
  - 요소밍
  - 우주의 먼지
  - 원콩
  - 유메
  - 입력됴
  - 제제
  - 지은
  - 창꼬
  - 카소
  - 카에
  - 탄
  - 토깅
  - 파카
  - 펄
  - 프리이
  - 플샤
  - 하내린
  - 하람
  - 호나수
  - 홍률푸딩
  - 희세
  - 히메ひめ
  - F
  - kimleon1991
  - Non
  - 묭
  - 우냑
  - 쾌속
  - 양말
  - 옐옐비
  - 담
  - 히츄
  - 수념
  - 이사야
  - 겨울
  - 그랑
  - 해
  - 햇뇽
  - 폭서
  - 젤리
  - 포에
  - 공늠
  - 카에데
  - 엘리
  - 유에
  - 죠리퐁
  - 적운
  - 뭉자
  - 사마
  - NORI
  - 화양
  - 매화
  - 고연희
  - 야토
  - 히둥이에요
  - 녤룸
  - 히메
  - 가다랑어
  - 은유
  - 루땅
  - 히토리
  - 하리
  - 타로
  - Chinya
  - 나나
  - 휴님
  - 마리링
  - sobol_69
  - luniie
  - 리윤
  - 챠무
  - HEE
  - 보민
  - 루리
  - 랑룬
  - 뉴
  - 하무추
  - peyz
  - 괴물왕
  - 이밤
  - 초능력자
  - 네기
  - 꼬꼬
  - 치에
  - 김매화
  - 아덜
  - 코스모스
  - 마야
  - 레임(사진사)
  - EHAN
  - 슈슈
  - 한겸
  - 마늘
  - atelier
  - 푸들들
  - 슈타
  - 유감
  - 차댬
  - 사야
  - 고리
  - 포치
  - 강서문
  - 흑랑
  - 쉐리
  - 윤슬
  - 다정
  - 아연
  - 사담추
  - 미나리
  - 메케메케
  - Ru
  - 차몽
  - 미잉
  - 레아
  - 하영민
  - 으네
  - 관시
  - 쌉
  - 쩝
  - 선홍
  - 체인
  - 버터
  - 제덴
  - 에테루
  - 소나
  - 아이피
  - 베베
  - 주짱
  - 월향
  - 솔이
  - 꼬묘
  - 설희
  - 김마루
  - 수달
  - 쪼리
  - 치하루
  - 리즈
  - 요후카
  - 옴마이
  - 로이
  - 단현
  - 아리
  - 세나
  - pinyo
  - 도아
  - 퍼비
  - 씨즈
  - 김멈
  - 스
  - 케로
  - 나영
  - 강끼룩
  - 영
  - 미피링
  - 민저
  - 최멍바
  - 아란
  - 민서
  - 혜와
  - Dominala
  - 븐개
  - 윤달
  - 민식
  - 미엘
  - 라힌
  - 연
  - 룬쿠
  - 한셀
  - 세이
  - 노노
  - 린아
  - 호시
  - 겟겟
  - 네루
  - 시스
  - 무박신
  - 아이
  - 이름
  - 뮤즈
  - 퍼푼
  - 도나츠
  - 엔니
  - 바삭
  - 민하
  - 하루미
  - 도쿠
  - 퐁퐁
  - 푸딩
  - 륨
  - 김로아
  - 시호
  - 탱여
  - 블루나
  - honey bee
  - 토토
  - 비열
  - 구이
  - 냠
  - 젠
  - 듀듀
  - 리밋치
  - 산호
  - 시헌
  - 토노
  - 설
  - 유화
  - 테오
  - 빙빙
  - 뇨롱
  - 파랑치타
  - 민유화
  - 단지
  - 아이카
  - 연우
  - 긴쟈
  - 코비비
  - 청삼
  - 갱강
  - sshoda
  - 자두
  - 군걀
  - YejiLu
  - 500
  - 오짱
  - 조림
  - 네오시안
  - 볼탱탱귤선생
  - 다오니
  - 죠미
  - 우르르롹끼
  - 다온
  - 리무
  - 아이런
  - 삼이
  - 한현
  - 치이
  - 플메
  - 예지
  - 레드로스
  - 키네
  - 히지
  - 유케이
  - 미유
  - 교토
  - 세렌
  - 뇨밍
  - 루나
  - 온유
  - 김히로
